browser=edge
loginUrl=https://login.salesforce.com/
username=manpreet@prizm.demo.nz
password=Password@1
emailAddress=manpreet.s@finspectra.com
emailPassword=Prizm$2026
accountName=GenePoint
requestedLoanAmount=5000000

creditLimitAmount=5000000
rate=7.5
noOfPayments=12

CollateralSubFamily=Single Family Home
CollateralName=Demo Collateral
CollateralSecurityRanking=First Mortgage
CollateralAddress=Auckland
