browser=chrome
loginUrl=https://login.salesforce.com/
username=manpreet@prizm.demo.nz
password=Password@1
emailAddress=manpreet.s@finspectra.com
emailPassword=Prizm$2026
accountName=GenePoint
requestedLoanAmount=5000000

creditLimitAmount=5000000
rate=7.5
noOfPayments=12

CollateralSubFamily=Single Family Home
CollateralName=Demo Collateral
CollateralSecurityRanking=First Mortgage
CollateralAddress=Auckland
PropertyType=Residential House
Location=Urban
Valuation=5000000
CompleteValuation=8000000

approvalProcessComment=Please approve this to fund the application customer has a good credit score and giving high value security
userName=manpreet
approvalProcessApprovedComment=Approved please proceed further
Reason=No need of this Approval